### ISSUE TITLE
Error: ENOENT, The system cannot find the file specified.

### ISSUE THREAD

**Issue by kwerty** [skid/node-t#11]
Running latest Node on Windows

var tmpl = template.fromFile("/templates/homepage.html");
var tmpl = template.fromFile("./templates/homepage.html");
var tmpl = template.fromFile("templates/homepage.html");

None of the above lines work, they all give an error like the error below -

Error: ENOENT, The system cannot find the file specified. '//./templates/homepage.html'

Fix: Open up index.js and change the root -

```
ROOT = "./",
```

Works now

**Comment by skid** [comment]
Did just that :) Can't test it right now, but I trust your judgement.
